language: php
php:
  - 7.1
  - 7.2

before_install:
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - composer install

script:
  - vendor/bin/phpunit
