language: php
php:
  - 5.6
  - 7.0
services:
  - redis-server
  
before_install:
  - phpenv config-rm xdebug.ini
  - before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
before_script:
  - composer install

script:
  - vendor/bin/phpunit
